# Reddit dataset

In [40]:
from datetime import datetime
# start from the file after preproessing
reddit_df = pd.read_csv('TXA/preprocessed_reddit.csv')

In [41]:
# convert created_utc column in to date_time format
reddit_df['created_utc'] = pd.to_datetime(reddit_df['created_utc'])
# split the date_time column into date and time to support filterting
reddit_df['date'] = reddit_df['created_utc'].dt.date
reddit_df['time'] = reddit_df['created_utc'].dt.time

In [42]:
reddit_df.head()

,topic_title,id,author,subreddit,link_id,parent_id,num_comments,upvotes,created_utc,text,Tokens,mapped_tokens,date,time
0,Oh how offices have changed,1fy22yp,naixelsyd,remotework,1fy22yp,NaN,435,4911,2024-10-07 07:32:09,for those who don't know 2030 years ago commut...,"['know', '2030', 'years', 'ago', 'commuting', ...","['know', '2030', 'years', 'ago', 'commuting', ...",2024-10-07,07:32:09
1,Oh how offices have changed,lqqyui9,fejobelo,remotework,1fy22yp,t3_1fy22yp,0,581,2024-10-07 08:33:42,back in the day every time we stayed working a...,"['back', 'day', 'every', 'time', 'stayed', 'wo...","['back', 'day', 'every', 'time', 'stayed', 'wo...",2024-10-07,08:33:42
2,Oh how offices have changed,lqrf0ak,TrekJaneway,remotework,1fy22yp,t3_1fy22yp,0,138,2024-10-07 11:27:56,and a pensiondont forget a pension but that wa...,"['pensiondont', 'forget', 'pension', 'still', ...","['pensiondont', 'forget', 'pension', 'still', ...",2024-10-07,11:27:56
3,Oh how offices have changed,lqrjvzl,CZ1988_,remotework,1fy22yp,t3_1fy22yp,0,69,2024-10-07 12:08:10,20 years ago was still a cube farm you did get...,"['20', 'years', 'ago', 'still', 'cube', 'farm'...","['20', 'years', 'ago', 'still', 'cube', 'farm'...",2024-10-07,12:08:10
4,Oh how offices have changed,lqrrh6n,Ok-Combination-5201,remotework,1fy22yp,t3_1fy22yp,0,17,2024-10-07 13:03:07,the movie office space came out 25 years ago t...,"['movie', 'office', 'space', 'came', '25', 'ye...","['movie', 'office', 'space', 'came', '25', 'ye...",2024-10-07,13:03:07

In [43]:
# dataset's shape before filtering
reddit_df.shape

(173699, 14)

In [44]:
reddit_df['date'] = pd.to_datetime(reddit_df['date'], errors='coerce')

# create a datetime object for April 30, 2023
filter_date = pd.to_datetime('2023-04-30')

# apply the filter condition (rows after April 30, 2023)
reddit_filtered = reddit_df[reddit_df['date'] > filter_date]

In [45]:
# # dataset's shape after filtering
reddit_filtered.shape

(157519, 14)

In [46]:
# remove the unnesessary columns to shrink the file
reddit_filtered = reddit_filtered.drop(['date','time'], axis=1)

In [47]:
reddit_filtered.to_csv('filtered_data_reddit.csv', index=False, encoding='utf-8-sig')

In [49]:
reddit_filtered.head()

,topic_title,id,author,subreddit,link_id,parent_id,num_comments,upvotes,created_utc,text,Tokens,mapped_tokens
0,Oh how offices have changed,1fy22yp,naixelsyd,remotework,1fy22yp,NaN,435,4911,2024-10-07 07:32:09,for those who don't know 2030 years ago commut...,"['know', '2030', 'years', 'ago', 'commuting', ...","['know', '2030', 'years', 'ago', 'commuting', ..."
1,Oh how offices have changed,lqqyui9,fejobelo,remotework,1fy22yp,t3_1fy22yp,0,581,2024-10-07 08:33:42,back in the day every time we stayed working a...,"['back', 'day', 'every', 'time', 'stayed', 'wo...","['back', 'day', 'every', 'time', 'stayed', 'wo..."
2,Oh how offices have changed,lqrf0ak,TrekJaneway,remotework,1fy22yp,t3_1fy22yp,0,138,2024-10-07 11:27:56,and a pensiondont forget a pension but that wa...,"['pensiondont', 'forget', 'pension', 'still', ...","['pensiondont', 'forget', 'pension', 'still', ..."
3,Oh how offices have changed,lqrjvzl,CZ1988_,remotework,1fy22yp,t3_1fy22yp,0,69,2024-10-07 12:08:10,20 years ago was still a cube farm you did get...,"['20', 'years', 'ago', 'still', 'cube', 'farm'...","['20', 'years', 'ago', 'still', 'cube', 'farm'..."
4,Oh how offices have changed,lqrrh6n,Ok-Combination-5201,remotework,1fy22yp,t3_1fy22yp,0,17,2024-10-07 13:03:07,the movie office space came out 25 years ago t...,"['movie', 'office', 'space', 'came', '25', 'ye...","['movie', 'office', 'space', 'came', '25', 'ye..."